### Crear Usuario
POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
    "nombre": "pepe",
    "apellido": "Hernández",
    "email": "oscar@gmail.com",
    "contrasenia": "Poter551147481$",
    "confirmarContrasenia": "Poter551147481$"
}

### Iniciar sesión
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "oscar@gmail.com",
    "contrasenia": "Poter551147481$"
}

### Obtener todos los usuarios
GET http://localhost:3000/user HTTP/1.1

### Crear un tablero
POST http://localhost:3000/tablero
Content-Type: application/json

{
	"idUsuario": "67c76eb589ff57316d3c81b6",
	"nombre": "Proyecto",
    "listas": [{
        "nombre": "Por hacer",
        "tarjetas": [{
            "nombre": "Tarea 1",
            "description": "lorem",
        }]
    }]
}

### Obtener tableros por id de usuario
GEt http://localhost:3000/tablero?67c76eb589ff57316d3c81b6

### Eliminar Tablero
DELETE http://localhost:3000/tablero/67d60614f622b44bf0133987

### Eliminar Listas
DELETE http://localhost:3000/lista/67e47ee58958ef794d2691b4

### Crear Tarjeta
POST http://localhost:3000/tarjeta/67e4d2108ed20ac20751ea2e
Content-Type: application/json
{
    "titulo": "Tarea 1",
    "descripcion": "Terminar la tarea",
    "prioridad": "Alto",
}